name: Caffe Mocha

on:
  push:

jobs:
  main:
    name: ESLint & Prettier
    runs-on: ubuntu-latest

    steps:
      - name: actions/checkout
        uses: actions/checkout@v2
      - name: Yarn Cache
        uses: c-hive/gha-yarn-cache@v2
      - name: Install Dependencies (Yarn)
        run: yarn install
      - name: Build Test
        run: yarn build
      - name: ESLint & Prettier Check
        run: yarn lint
